author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /humpty-dumpty
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    extra_js:
    - deepzoom.js
    - openseadragon.min.js
    - volume-page.js
    - hammer.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
homepage_image: http://digital.library.wayne.edu/readux/books/wayne:DenslowsH1903b48447389_Readux_VirtualVolume/pages/wayne:DenslowsH1903b48447389_Readux_VirtualPage_1/single-page/
image_size:
  page:
    height: 1000
    width: 762
  small-thumbnail:
    height: 100
    width: 76
  thumbnail:
    height: 300
    width: 228
permalink: pretty
publication_info:
  author: null
  date: '2016'
  editors: []
  tei_xml: tei.xml
  title: Humpty Dumpty, an annotated digital edition
show_annotation_author: true
source_info:
  author: null
  date: '1903'
  pdf_url: http://digital.library.wayne.edu/readux/books/wayne:DenslowsH1903b48447389_Readux_VirtualVolume/pdf/
  title: Humpty Dumpty
  url: http://digital.library.wayne.edu/readux/books/wayne:DenslowsH1903b48447389_Readux_VirtualVolume/
  via_readux: true
tagline: ', an annotated digital edition'
title: Humpty Dumpty
url: http://ghukill.github.io
version: 0.6
